# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad04214ba3b98b2df99cc821438e93d5645f27cc84274e0bbd2fd24749dad471441318d91c818507caf01934e791e8dc4da649fd6aedbc0826777b65b7ed97e5

test:
  secret_key_base: 7cc85f2af7c7445300b087763e7cd25c5886b0926bc782c7edd324ecd1890327d672e616e998dde78275d35e08663178e75b8421c0819c149bbf74f1b247e078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
